# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version:  11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
  CD:
      runs-on: ubuntu-latest
      needs: build

      steps:
      - uses: actions/checkout@v2

      - name: use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: gradlew Full Authorization
        run: chmod 777 gradlew

      - name: Clean and Build
        run: ./gradlew clean build -x test

      - name: Create Docker Image
        run: docker build --tag gangwon .
#        run: docker build --tag pick-saturn .

      - name: Upload to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 0816jinjin/saturn
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
             
